meta_product_name: "Product Name"
mata_title: "Product name - Product tagline"
meta_description: "Relevant description"
meta_image: "cover.png" #this should exist in the assets pipeline under images
twitter_account: "@product_twitter_account" #This is required for twitter cards
